config/routes.rb
Rails.application.routes.draw do
  get 'images/show'
  get 'contact', to: 'contact#new'
  post 'contact', to: 'contact#create'
  get 'explore', to: 'explore#index'
  get 'alerts', to: 'alerts#index'
  post '/save_changes', to: 'alerts#save_changes'

  namespace :api do
    post '/new_picture', to: 'alerts#new_picture'
  end

  resource :session
  resource :registration
  resource :password_reset
  resource :password
  resources :alerts

  resources :pet_submissions do
    resources :comments, only: [:create]
  end

  resources :pet_submissions do
    member do
      patch 'close'
    end
  end

  get 'user_submissions', to: 'pet_submissions#user_submissions'
  get 'breeds/:breed/:image_name', to: 'images#show', as: 'breed_image'
  get 'explore/image', to: 'images#show', as: :explore_image
  get '/faq', to: 'faq#index'

  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :pet_submission
  validates :body, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :subject, presence: true
    validates :email, presence: true
    validates :message, presence: true
end
  

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/folder.rb
class Folder < ApplicationRecord
    has_many :subscriptions
    has_many :users, through: :subscriptions
end

app/models/image_metadata.rb
class ImageMetadata < ApplicationRecord
    attribute :breed, :string
    attribute :image_name, :string
    attribute :location, :string
    attribute :time, :string
  
    validates :breed, presence: true
    validates :image_name, presence: true
    validates :location, presence: true
    validates :time, presence: true
  end
  

app/models/location.rb
class Location < ApplicationRecord
    has_many :subscriptions
    has_many :users, through: :subscriptions
end

app/models/pet_submission.rb
class PetSubmission < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    has_many :comments, dependent: :destroy
  
    validates :title, presence: true
    validates :body, presence: true
    validates :image, presence: true
end
  

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :location
  belongs_to :folder
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :pet_submissions
    has_and_belongs_to_many :locations, join_table: :locations_users

    has_many :subscriptions
    has_many :locations, through: :subscriptions
    has_many :folders, through: :subscriptions

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address!"}
    validates :username, presence: true, uniqueness: { case_sensitive: false }
    normalizes :email, with: ->(email) {email.strip.downcase}

    generates_token_for :password_reset, expires_in: 15.minutes do
        password_salt&.last(10)
    end

    generates_token_for :email_confirmation, expires_in: 24.hours do
        email
    end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :authenticate_user!

  def index
    @locations = Location.all
    @folders = Folder.all
    @user_subscriptions = current_user.subscriptions.includes(:location, :folder)
  end

  def save_changes
    selected_location_ids = params[:locations]
    selected_folder_ids = params[:folders]

    Subscription.transaction do
      selected_location_ids.each do |location_id|
        selected_folder_ids.each do |folder_id|
          # Find or create a subscription for the user, location, and folder combination
          subscription = current_user.subscriptions.find_or_initialize_by(location_id: location_id, folder_id: folder_id)
          subscription.save
        end
      end
    end

    redirect_to alerts_path, notice: 'Changes saved successfully!'
  end

  def destroy
    subscription = current_user.subscriptions.find(params[:id])
    subscription.destroy

    redirect_to alerts_path, notice: 'Alert deleted successfully!'
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def new
        @contact = Contact.new
    end
  
    def create
      @contact = Contact.new(contact_params)
      if @contact.save
        redirect_to root_path, notice: 'Message sent successfully.'
      else
        redirect_to root_path, alert: 'Failed to send message. Please try again'
      end
    end
  
    private
  
    def contact_params
      params.require(:contact).permit(:subject, :email, :message)
    end
    
  end
  

app/controllers/faq_controller.rb
class FaqController < ApplicationController
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def show
    # Retrieve breed and image_name from the params
    breed = params[:breed]
    image_name = params[:image_name]

    # Assuming your images are stored in 'app/assets/images/DogFrames'
    image_path = "DogFrames/#{breed}/#{image_name}.jpg"  # Change the extension based on your images

    # Extract location and time from the image_name
    location, time = image_name.split('_', 2)

    # Save or use the location and time as needed
    # Example: Save them to the database
    ImageMetadata.create(breed: breed, location: location, time: time)

    # Render the show view with necessary data
    render 'show', locals: { breed: breed, image_name: image_name, image_path: image_path, location: location, time: time }
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Petcon - Reunite lost pets with their owners">
  <meta name="keywords" content="pet, lost pets, reunite, community">
  <meta name="author" content="Uziel Augusto Luna">

  <title>Petcon</title>

  <link rel="icon" href="/favicon.ico" type="image/x-icon">

  <!-- Bootstrap CSS from CDN with integrity and crossorigin attributes -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <!-- Own CSS files if needed -->
  <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>

  <!-- Importmap for JavaScript - if you're using JavaScript modules -->
  <%= javascript_importmap_tags %>

  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css', integrity: 'sha384-QHdnz0I0zlfqVV0GnVMF7FnRm67tFLeImakqQ+8enOpAo3rI/TF8eCe2Oh5PIVpU', crossorigin: 'anonymous' %>


  <!-- CSRF Meta Tags for Rails -->
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>

<body>
  <!-- Navbar Partial -->
  <%= render partial: "shared/navbar" %>

  <div class="container">
    <!-- Flash Messages Partial -->
    <%= render partial: "shared/flash" %>

    <!-- Page Content -->
    <%= yield %>
  </div>

  <!-- Bootstrap JS from CDN with integrity and crossorigin attributes -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #3498db;">
    <div class="container-fluid">
        <%= link_to image_tag("favicon.ico", alt: "Favicon"), root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Explore", explore_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Contact", contact_path, class: "nav-link" %>
                </li>
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to "Alerts", alerts_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "User Submissions", user_submissions_path, class: "nav-link" %>
                    </li>
                <% end %>
                <li class="nav-item">
                    <%= link_to "View lost pets", pet_submissions_path, class: "nav-link" %>
                </li>
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to "Submit lost pet", new_pet_submission_path, class: "nav-link" %>
                    </li>
                <% end %>
                <li class="nav-item">
                    <%= link_to "FAQ", faq_path, class: "nav-link" %>
                </li>
            </ul>

            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to Current.user.username, edit_password_path, class: "nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= button_to "Logout", session_path, method: :delete, class: "btn btn-outline-light" %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign Up", new_registration_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Login", new_session_path, class: "nav-link" %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>